version: '3.8'

services:
  backend:
    container_name: pupilove_backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./pupilove/backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_IP=host.docker.internal
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    extra_hosts:
      - "host.docker.internal:host-gateway"


  frontend:
    container_name: pupilove_frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8001:8001"
    volumes:
      - ./pupilove/frontend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://backend:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
